GET http://localhost:8089/api/kunde/4
Accept: application/json

###
GET http://localhost:8089/api/kunde
Accept: application/json

###
POST http://localhost:8089/api/kunde
Content-Type: application/json

{
  "email": "latof@fth.com"
}
